# -*- coding: utf-8 -*-
"""simpleapp.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16XYkV43FD2GW_kWso-YAydiYODWWkDrW
"""

!pip install streamlit

import streamlit as st
import pandas as pd

st.write("""
# SIMPLE TEXT SIMILARITY APP 

Compare two sentences and check it out!
""")