# -*- coding: utf-8 -*-
"""simpleapp.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16XYkV43FD2GW_kWso-YAydiYODWWkDrW
"""

#!pip install streamlit

import streamlit as st
import pandas as pd

st.write("""
# SIMPLE TEXT SIMILARITY APP 

Compare two sentences and check it out!
""")

col1, col2, col3 = st.beta_columns(3)
with col1:
    word_1 = st.text_input('word 1', 'shirt')
with col2:
    word_2 = st.text_input('word 2', 'jeans')
with col3:
    word_3 = st.text_input('word 3', 'apple')
